### ISSUE TITLE
Hao to use it?

### ISSUE THREAD

**Issue by Nova555** [TheOnceAndFutureSmalltalker/ros_map_editor#1]
I perform "python MapEditor.py test-nova". The error is: 
"test-nova.pgm
MapEditor.py:164: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for doc in docs:
"
And I Click UI window. The soft will exit. The error is:
"Traceback (most recent call last):
  File "MapEditor.py", line 197, in mapClick
    self.im.putpixel((x,y), val)    
  File "/home/nova/.local/lib/python2.7/site-packages/PIL/Image.py", line 1753, in putpixel
    return self.im.putpixel(xy, value)
TypeError: integer argument expected, got float"

**Comment by Nova555** [comment]
I solved the. using python3
